<?php

/*
 * Contract clause templates. {{placeholders}} are filled by ContractGenerator from approved project data; unknown placeholders
 * make generation fail (a clause is never silently blank). Clause code SHARIAH_REVIEW is the review block: it is excluded from the
 * terms hash a reviewer approves. These texts are the platform's implementation of the current product specification; they are
 * NOT legal advice, NOT a fatwa and NOT Shariah certification, and every template version starts with a PENDING Shariah review.
 */
$common = fn (string $title) => [
    ['HEADING', $title, "Agreement reference {{reference}}. Contract {{contract_number}}. Version {{document_version}}. Template {{template_code}} version {{template_version}}. Date {{doc_date}}."],
];

$review = ['SHARIAH_REVIEW', 'Shariah review', '{{shariah_review_block}}'];
$disclaimer = ['DISCLAIMER', 'Nature of this document', 'This agreement was generated by software from the approved project terms and the approved template version shown above; its clauses cannot be edited by a party. It is not legal advice, not a fatwa and not Shariah certification. A recorded Shariah review, if any, applies to this exact structure and template version only. Enforceability under the law of Bangladesh is subject to review by qualified counsel.'];
$disputes = ['DISPUTES', 'Dispute resolution', 'Disputes arising from this agreement are resolved through the dispute-resolution mechanism approved for this project, under the applicable law of Bangladesh.'];

return [
    'MUDARABAH-MASTER' => ['aqd' => 'MUDARABAH', 'kind' => 'MASTER_AQD', 'title' => 'Mudarabah Agreement', 'clauses' => array_merge($common('MUDARABAH AGREEMENT'), [
        ['PARTIES', 'Parties', '{{business_legal_name}} (registration {{business_registration}}; identity verification: {{business_kyc}}), represented by {{representative}}, is the Mudarib (entrepreneur / working partner). Each person who accepts this Mudarabah by signing an individual participation agreement for an amount is a Rabb-ul-Mal (capital provider). {{platform_role_text}}'],
        ['RECITALS', 'Recitals', 'The Mudarib proposes to carry on this business: {{business_activity}}. The Rabb-ul-Mal provides capital (Ras-ul-Mal) and the Mudarib provides management and effort. Purpose of the project: {{project_purpose}}.', null, ['MUD-CAPITAL-DELIVERY']],
        ['DEFINITIONS', 'Definitions', 'Aqd means contract. Mudarabah means a contract in which one party provides capital and the other provides effort, sharing actual profit by an agreed ratio. Rabb-ul-Mal means the capital provider. Mudarib means the entrepreneur / working partner. Ras-ul-Mal means the Mudarabah capital. Profit means the actual profit determined at the final calculation, never an amount promised in advance. Fault means misconduct, negligence or breach of the agreed terms.'],
        ['SUBJECT', 'Subject matter', 'Business activity: {{business_activity}}. Permitted activities: {{permitted_activities}}. Prohibited activities: {{prohibited_activities}}.'],
        ['CAPITAL', 'Capital', 'The Ras-ul-Mal is {{capital_required}}. The minimum participation of a Rabb-ul-Mal is {{minimum_amount}}{{maximum_text}}. Purpose of the capital: {{capital_purpose}}. The capital is delivered to the Mudarib only after this agreement is executed, the project is fully funded and the delivery is recorded. Conditions of delivery: {{capital_deployment_conditions}}. The capital remains at risk and is not a loan.', null, ['MUD-CAPITAL-DELIVERY']],
        ['PROFIT', 'Profit', 'Profit is the actual profit determined at the final calculation, measured on this basis: {{profit_basis_label}}. It is shared {{rabb_ratio}} to the Rabb-ul-Mal collectively and {{mudarib_ratio}} to the Mudarib. Methodology: {{profit_methodology}}. Measurement: {{measurement_label}}. No fixed amount, no percentage of the capital and no return is promised or guaranteed to any party.', null, ['MUD-PROFIT-RATIO', 'MUD-ADVANCES']],
        ['LOSS', 'Loss', 'An ordinary commercial loss is borne by the Rabb-ul-Mal to the extent of its capital, and the Mudarib loses its effort. The Mudarib does not guarantee the capital. No debt arises merely because the venture made a loss. The Mudarib is liable only where loss is caused by misconduct, negligence or breach, as defined in the clause on breach.', null, ['MUD-LOSS-RABB']],
        ['RESPONSIBILITIES', 'Responsibilities', 'The Mudarib: {{management_responsibilities}}. Reporting: {{reporting_obligations}} ({{reporting_frequency_label}}). Restrictions on the use of funds: {{use_of_funds_restrictions}}. Shariah compliance duties: {{shariah_compliance_duties}}. The Rabb-ul-Mal provides the capital as agreed and bears ordinary loss as stated above.'],
        ['RISK', 'Risk', 'The capital is exposed to the risks of the business, including: {{key_risks}}. The risk of the venture lies with the Rabb-ul-Mal as to capital and with the Mudarib as to effort.'],
        ['BREACH', 'Negligence, misconduct and breach', 'An ordinary commercial loss is not a breach. Negligence means: {{negligence_definition}}. Misconduct means: {{misconduct_definition}}. Breach means: {{breach_conditions}}. Fraud and unauthorised use of the capital are misconduct. Where fault is established through the agreed procedure, the Mudarib compensates the loss caused by it and is not entitled to remuneration for its effort. A recovery is compensation for the loss, not profit.', null, ['MUD-MUDARIB-FAULT']],
        ['SECURITY', 'Security for fault', 'Security limited to damages caused by fault or breach: {{security_for_fault}}.', 'security_for_fault', ['MUD-GUARANTEE-FAULT-ONLY']],
        ['INTERIM', 'Interim payments', 'Any interim payment is an advance against the final result and is settled at the final calculation. It is not final profit.', null, ['MUD-ADVANCES']],
        ['TERMINATION', 'Termination, liquidation and settlement', 'Term: {{duration_months}} months. Maturity and termination: {{maturity_conditions}}. Early termination: {{early_termination_rules}}. Liquidation and valuation: {{liquidation_valuation}}. Final determination of profit or loss: {{final_determination}}. Settlement: {{settlement_process}}.', null, ['MUD-ADVANCES']],
        $disputes, $review, $disclaimer,
    ])],

    'MUDARABAH-PARTICIPATION' => ['aqd' => 'MUDARABAH', 'kind' => 'PARTICIPATION', 'title' => 'Mudarabah Participation Agreement', 'clauses' => array_merge($common('MUDARABAH PARTICIPATION AGREEMENT'), [
        ['PARTIES', 'Parties', '{{investor_name}} (investor reference {{investor_ref}}; identity verification: {{investor_kyc}}) is the Rabb-ul-Mal (capital provider). {{business_legal_name}} (registration {{business_registration}}) is the Mudarib (entrepreneur / working partner). {{platform_role_text}}'],
        ['BASIS', 'Basis', 'This participation accepts the Mudarabah Agreement {{master_reference}} (document hash {{master_hash}}) on its terms, which the Rabb-ul-Mal has read in full.'],
        ['CAPITAL', 'Capital', 'The Rabb-ul-Mal participates with {{amount}} of the Ras-ul-Mal of {{capital_required}}, that is {{participation_share}} of it. The amount is committed from the Rabb-ul-Mal\'s wallet, remains at risk and is delivered to the Mudarib only when the delivery of the capital is recorded.', null, ['MUD-CAPITAL-DELIVERY']],
        ['PROFIT', 'Profit', 'The Rabb-ul-Mal shares in the Rabb-ul-Mal collective share of {{rabb_ratio}} of actual profit in proportion to its participation. No profit, return or capital is guaranteed.', null, ['MUD-PROFIT-RATIO']],
        ['LOSS', 'Loss', 'The Rabb-ul-Mal understands that an ordinary commercial loss reduces its capital, that the Mudarib does not guarantee the capital, and that no debt of the Mudarib arises from an ordinary loss. The Mudarib is liable only for established misconduct, negligence or breach.', null, ['MUD-LOSS-RABB', 'MUD-MUDARIB-FAULT']],
        ['ACCEPTANCE', 'Offer and acceptance', 'The Mudarib offered the Mudarabah by executing the master agreement. The Rabb-ul-Mal accepts it for the amount above by signing this agreement.'],
        $review, $disclaimer,
    ])],

    'MUSHARAKAH-MASTER' => ['aqd' => 'MUSHARAKAH', 'kind' => 'MASTER_AQD', 'title' => 'Musharakah Agreement', 'clauses' => array_merge($common('MUSHARAKAH AGREEMENT'), [
        ['PARTIES', 'Parties', '{{business_legal_name}} (registration {{business_registration}}; identity verification: {{business_kyc}}), represented by {{representative}}, is the business Musharik (partner). Each person who accepts this Musharakah by signing an individual participation agreement is an investor Musharik. {{platform_role_text}}'],
        ['RECITALS', 'Recitals', 'The partners establish a partnership for this activity: {{project_activity}}. Purpose: {{project_purpose}}.'],
        ['DEFINITIONS', 'Definitions', 'Aqd means contract. Musharakah means a partnership in which each partner contributes capital and shares actual profit by the agreed ratio and loss in proportion to capital. Musharik means a partner. Capital contribution means the capital each partner pays into the partnership. Profit-sharing ratio is the agreed share of actual profit. Loss-sharing ratio is the capital contribution ratio.'],
        ['SUBJECT', 'Subject matter', 'Partnership activity: {{project_activity}}. Permitted activities: {{permitted_activities}}. Prohibited activities: {{prohibited_activities}}.'],
        ['CAPITAL', 'Capital contributions', 'Total partnership capital is {{total_capital}}. The investor Musharik side contributes {{investor_contribution}}. The business Musharik contributes {{business_contribution}} ({{contribution_method_label}}) on or before {{business_contribution_date}}, before operations start, with evidence reference {{contribution_evidence}}. Each contribution is an ownership interest in the partnership, remains at risk, and is not a loan to any other partner. Capital ratio (investors / business): {{capital_ratio}}.', null, ['MUS-CAPITAL-TIMING', 'MUS-NO-CAPITAL-GUARANTEE']],
        ['PROFIT', 'Profit', 'Actual profit is shared {{investor_profit_ratio}} to the investor side and {{business_profit_ratio}} to the business Musharik, which is the agreed profit-sharing ratio and need not equal the capital ratio. Basis: {{profit_basis_label}}. Methodology: {{profit_methodology}}. Measurement: {{measurement_label}}. No profit is guaranteed to any partner and no partner is excluded from profit.', null, ['MUS-PROFIT-RATIO', 'MUS-NO-PROFIT-GUARANTEE']],
        ['LOSS', 'Loss', 'Each partner bears an ordinary loss in proportion to its capital contribution, that is {{capital_ratio}} (investors / business). This cannot be changed by agreement. No partner or manager guarantees the capital of another partner, and no debt arises between partners from an ordinary loss.', null, ['MUS-LOSS-CAPITAL', 'MUS-NO-CAPITAL-GUARANTEE']],
        ['GOVERNANCE', 'Management and governance', 'Management rights: {{management_rights}}. Partner authority and limits: {{partner_authority}}. Withdrawal restrictions: {{withdrawal_restrictions}}. Ownership of partnership assets: {{asset_ownership}}. Distribution: {{distribution_rules}}. Exit: {{exit_rules}}.'],
        ['RISK', 'Risk', 'Partners are exposed to the risks of the partnership, including: {{key_risks}}.'],
        ['BREACH', 'Fault, negligence and breach', 'An ordinary commercial loss is not a breach. {{breach_conditions}}. A managing partner is liable only for loss caused by conduct contrary to this agreement or by its fault.', null, ['MUS-MANAGER-FAULT']],
        ['INTERIM', 'Interim payments', 'Any interim payment to a partner is an advance settled at the final calculation. It is not final profit.', null, ['MUS-ADVANCES']],
        ['TERMINATION', 'Dissolution, liquidation and settlement', 'Term: {{duration_months}} months. Dissolution and liquidation: {{dissolution_rules}}. The final result is determined on liquidation, actual or by valuation, and settled accordingly.', null, ['MUS-ADVANCES']],
        ['DISPUTES_TERM', 'Dispute resolution', '{{dispute_resolution}}'],
        $review, $disclaimer,
    ])],

    'MUSHARAKAH-PARTICIPATION' => ['aqd' => 'MUSHARAKAH', 'kind' => 'PARTICIPATION', 'title' => 'Musharakah Participation Agreement', 'clauses' => array_merge($common('MUSHARAKAH PARTICIPATION AGREEMENT'), [
        ['PARTIES', 'Parties', '{{investor_name}} (investor reference {{investor_ref}}; identity verification: {{investor_kyc}}) is an investor Musharik (partner). {{business_legal_name}} (registration {{business_registration}}) is the business Musharik. {{platform_role_text}}'],
        ['BASIS', 'Basis', 'This participation accepts the Musharakah Agreement {{master_reference}} (document hash {{master_hash}}) on its terms, which the investor Musharik has read in full.'],
        ['CAPITAL', 'Capital contribution', 'The investor Musharik contributes {{amount}} of the investor-side capital of {{investor_contribution}}, that is {{participation_share}} of it, as part of the total partnership capital of {{total_capital}}. The contribution remains at risk and is paid in with the delivery of the partnership capital being recorded.', null, ['MUS-CAPITAL-TIMING']],
        ['PROFIT', 'Profit and loss', 'The investor Musharik shares in the investor-side profit share of {{investor_profit_ratio}} of actual profit in proportion to its contribution, and bears loss in proportion to its capital contribution ({{capital_ratio}}). Nothing is guaranteed and no partner guarantees another partner\'s capital.', null, ['MUS-PROFIT-RATIO', 'MUS-LOSS-CAPITAL']],
        ['ACCEPTANCE', 'Offer and acceptance', 'The business Musharik offered the partnership by executing the master agreement. The investor Musharik accepts it for the amount above by signing this agreement.'],
        $review, $disclaimer,
    ])],

    'MURABAHA-MASTER' => ['aqd' => 'MURABAHA', 'kind' => 'MASTER_AQD', 'title' => 'Murabaha Purchase Request and Terms', 'clauses' => array_merge($common('MURABAHA PURCHASE REQUEST AND TERMS'), [
        ['PARTIES', 'Parties', '{{business_legal_name}} (registration {{business_registration}}; identity verification: {{business_kyc}}), represented by {{representative}}, is the requesting party and prospective buyer. The seller is the party that will acquire the asset and sell it under the Murabaha sale agreement. {{platform_role_text}}'],
        ['NATURE', 'Nature of this document', 'This document records a purchase request and the proposed terms of a later Murabaha sale. It is not the sale. The sale is a separate contract made only after the seller has acquired, owned and taken possession of the asset.', null, ['MUR-POSSESSION-BEFORE-SALE']],
        ['DEFINITIONS', 'Definitions', 'Aqd means contract. Murabaha means a sale at the seller\'s disclosed cost plus a disclosed profit. Qabd means possession. Wa\'d means a promise. Wakalah means agency; a Wakil is an agent and the Muwakkil is the principal. Disclosed cost is the price the seller paid the supplier.'],
        ['ASSET', 'Asset', 'Asset: {{asset_name}}. Specification: {{asset_description}}. Quantity: {{quantity}}. Expected unit cost: {{unit_cost}}. Supplier: {{supplier}}. Requested purchase terms: {{requested_purchase_terms}}. Delivery requirements: {{delivery_requirements}}.'],
        ['PROMISE', 'Promise (wa\'d)', 'A promise is used before the sale. Type: {{promise_type_label}}. Promisor: {{promisor_label}}. Conditions: {{promise_conditions}}. A promise is not the sale and does not replace it. A mutual promise is permissible only with an option for one or both parties. Breach of a binding promise is compensated by actual damages only, never a penalty.', 'use_promise', ['MUR-PROMISE', 'MUR-PROMISE-BREACH']],
        ['ACQUISITION', 'Acquisition, ownership and possession', 'The seller acquires the asset from the supplier in its own name ({{acquiring_party_label}}) and owns it before selling it. Supplier payment and evidence: {{payment_evidence_plan}}. Title evidence: {{title_evidence_plan}}. Ownership before the sale: {{ownership_info}}. Possession (qabd): {{qabd_type_label}}; {{possession_info}}. The seller bears the risk of the asset until delivery and for a period of at least {{risk_bearing_days}} days after possession before the sale.', null, ['MUR-POSSESSION-BEFORE-SALE', 'MUR-SUPPLIER-PAYMENT']],
        ['SALE_TERMS', 'Proposed sale terms', 'Disclosed profit: {{sale_profit}}. Instalments: {{installments}}. Payment schedule: {{payment_terms}}. Delivery: {{delivery_terms}}. The sale price will be the seller\'s disclosed acquisition cost plus the disclosed profit. There is no interest and no late-payment charge.', null, ['MUR-DISCLOSED-COST-PROFIT', 'MUR-NO-RECEIVABLE-BEFORE-SALE']],
        ['SEQUENCE', 'Required order', 'Request, promise (if any), Wakalah (if any), acquisition, ownership, possession (qabd), risk-bearing period, Murabaha sale agreement, receivable, instalments, settlement. No step may be skipped or replaced by another.', null, ['MUR-POSSESSION-BEFORE-SALE']],
        ['WAKALAH', 'Wakalah', 'Wakil appointments, if any, are separate agreements between a Muwakkil (principal) and a Wakil within a stated scope. The Wakil may not sell or consume the asset before the principal sells it.', null, ['MUR-AGENT-NO-DISPOSAL', 'WAK-DEFINITION']],
        ['RISK', 'Risk', 'Risks of the transaction, as disclosed by the requesting party: {{key_risks}}.'],
        $disputes, $review, $disclaimer,
    ])],

    'MURABAHA-SALE' => ['aqd' => 'MURABAHA', 'kind' => 'MURABAHA_SALE', 'title' => 'Murabaha Sale Agreement', 'clauses' => array_merge($common('MURABAHA SALE AGREEMENT'), [
        ['PARTIES', 'Parties', 'The seller is {{seller_name}}. The buyer is {{business_legal_name}} (registration {{business_registration}}; identity verification: {{business_kyc}}), represented by {{representative}}.'],
        ['RECITALS', 'Recitals', 'The seller has acquired the asset below from {{supplier}} (invoice {{invoice_reference}}, purchased on {{purchased_on}} for {{acquisition_cost}}), owns it (ownership acquired on {{ownership_on}}), and took possession ({{qabd_type_label}}) on {{possession_on}}. The seller has borne the risk of the asset since acquisition, including during the period of {{risk_period_days}} days before this sale.'],
        ['SUBJECT', 'Subject matter', 'The seller sells and the buyer buys: {{asset_name}} — {{asset_description}} — quantity {{quantity}}.'],
        ['PRICE', 'Disclosed cost, profit and price', 'The seller\'s disclosed acquisition cost is {{acquisition_cost}}. The disclosed profit is {{sale_profit}}. The sale price is {{sale_price}}, which is the disclosed cost plus the disclosed profit.', null, ['MUR-DISCLOSED-COST-PROFIT']],
        ['PAYMENT', 'Payment', 'The price is payable in {{installments}} instalments as follows: {{payment_terms}}. The price is a debt of the buyer arising from this sale. It does not increase for late payment and no interest is charged.', null, ['MUR-NO-RECEIVABLE-BEFORE-SALE']],
        ['DELIVERY', 'Delivery', '{{delivery_terms}}'],
        ['ACCEPTANCE', 'Offer and acceptance', 'The seller offers the sale on these terms and the buyer accepts it on the sale date {{sale_date}} by signing this agreement.'],
        ['DEFAULT', 'Default', 'A failure to pay an instalment when due is a breach to be remedied under the dispute-resolution mechanism; actual, documented damages only may be claimed, never a penalty or interest.'],
        $disputes, $review, $disclaimer,
    ])],

    'WAKALAH-APPOINTMENT' => ['aqd' => 'WAKALAH', 'kind' => 'WAKALAH', 'title' => 'Wakalah Appointment', 'clauses' => array_merge($common('WAKALAH APPOINTMENT'), [
        ['PARTIES', 'Parties', 'The Muwakkil (principal) is {{muwakkil_label}}. The Wakil (agent) is {{wakil_name}}. {{platform_role_text}}'],
        ['SUBJECT', 'Subject matter', 'The Wakil is appointed as {{role_label}} for the asset and project described as: {{scope}}. The underlying aqd is {{underlying_aqd}} (contract {{contract_number}}).'],
        ['AUTHORITY', 'Authority', 'The Wakil may perform only these acts: {{authority_list}}. Anything outside them is outside the Wakil\'s authority. The Wakil may not sell or consume the asset before the principal sells it, and acts for the principal, not for itself.', null, ['WAK-RESTRICTED', 'MUR-AGENT-NO-DISPOSAL']],
        ['ACCEPTANCE', 'Offer and acceptance', 'The Muwakkil offers this appointment. The Wakil accepts it by signing this document. Either party may revoke the Wakalah, and a revocation is recorded and takes effect from the time it is recorded.', null, ['WAK-DEFINITION', 'WAK-ACCEPTANCE']],
        ['DUTIES', 'Duties', 'The Wakil keeps evidence of every act, reports to the Muwakkil, and uploads the invoices and receipts connected with the acts performed.'],
        $disputes, $review, $disclaimer,
    ])],
];
